
tasks:
  
  - name: Build and test the Go project
    init: |
    go get && go build ./... && go test ./...

  - name: Setup Linear MCP Server and Cline
    init: |      
      # Install Linear MCP Server and register with Linear Cline
      # Note: make sure to set LINEAR_API_KEY in the Gitpod environment variables for the MCP server to work
      ./scripts/register-cline.sh

# Additional Gitpod configuration
ports:
  - port: 3000-8000
    onOpen: ignore

vscode:
  extensions:
    - golang.go
