# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM golang:1.23-alpine AS builder
WORKDIR /app

# Cache deps
COPY go.mod go.sum ./
RUN go mod download

# Copy source and build binary
COPY . .
RUN CGO_ENABLED=0 go build -o linear-mcp-go main.go

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/linear-mcp-go ./

# Expose port if needed, but MCP uses stdio
CMD ["./linear-mcp-go", "serve"]
